language: node_js
node_js: 10.15.3

jobs:
  include:
    - 
      name: coreclr-hosting linux
      os: linux
      stage: hosting core      
      before_install:
       - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
       - export DOTNET_CLI_TELEMETRY_OPTOUT=1
       - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
       - sudo dpkg -i packages-microsoft-prod.deb
       - sudo apt-get update
       - sudo apt-get install apt-transport-https
       - sudo apt-get update
       - sudo apt-get install dotnet-sdk-3.0   
      install: 
       - "cd coreclr-hosting"
       - npm install -g npm@'>=6.9.0'
       - npm i
      script:
       - npm run build-testapp
       # - export LD_DEBUG=files
       - npm run mocha
    - 
      name: coreclr-hosting osx
      os: osx   
      addons:
        homebrew:
          update: true
          casks:
           - dotnet-sdk
      install: 
       - "cd coreclr-hosting"
       - npm install -g npm@'>=6.9.0'
       - dotnet --version
       - npm i
      script:
       - npm run build-testapp
       - npm run mocha
    - 
      before_script:
        - "cd NodeHostEnvironment"
      language: csharp
      mono: none
      dotnet: 3.0.100
      script:
       - dotnet build
    -       
      stage: blazor hosting
      os: linux
      before_install:
       - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
       - export DOTNET_CLI_TELEMETRY_OPTOUT=1
       - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
       - sudo dpkg -i packages-microsoft-prod.deb
       - sudo apt-get update
       - sudo apt-get install apt-transport-https
       - sudo apt-get update
       - sudo apt-get install dotnet-sdk-3.0   
      install: 
       - "cd electron-blazor-glue"
       - npm install -g npm@'>=6.9.0'
       - npm i
      script:
       - npm run build-testapp
       # - export LD_DEBUG=files
       - npm run mocha
    - 
      before_script:
        - "cd ElectronHostedBlazor"
      language: csharp
      mono: none
      dotnet: 3.0.100
      script:
       - dotnet build