jobs:
  include:
    - 
      stage: hosting core
      install: nvm install 6.9.0
      node_js: 10.15.3
      before_script:
        - "cd coreclr-hosting"
      language: node_js
    - 
      before_script:
        - "cd NodeHostEnvironment"
      language: csharp
      mono: none
      dotnet: 3.0.100
      script:
       - dotnet restore
    - 
      stage: blazor hosting
      install: nvm install 6.9.0
      node_js: 10.15.3
      before_script:
        - "cd electron-blazor-glue"
      language: node_js
    - 
      before_script:
        - "cd ElectronHostedBlazor"
      language: csharp
      mono: none
      dotnet: 3.0.100
      script:
       - dotnet restore