jobs:
  include:
    - 
      stage: hosting core
      install: 
       - "cd coreclr-hosting"
       - npm install -g npm@'>=6.9.0'
       - npm i
      node_js: 10.15.3
      language: csharp
      mono: none
      dotnet: 3.0.100
      script: npm test
    - 
      before_script:
        - "cd NodeHostEnvironment"
      language: csharp
      mono: none
      dotnet: 3.0.100
      script:
       - dotnet build
    - 
      stage: blazor hosting
      install: 
       - "cd electron-blazor-glue"
       - npm install -g npm@'>=6.9.0'
       - npm i
      node_js: 10.15.3
      language: node_js
    - 
      before_script:
        - "cd ElectronHostedBlazor"
      language: csharp
      mono: none
      dotnet: 3.0.100
      script:
       - dotnet restore